import type { Metadata } from "next";
import { Roboto,Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./Providers";
import ReduxProvider from "./StoreProvider";
import Navbar from "./components/Navbar/page";
import { Toaster } from "@/components/ui/toaster"


const poppins = Poppins({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <ReduxProvider>
         
            <div>
              <Navbar />
            </div>
            {children}
            <Toaster/>
            </ReduxProvider>
         
        </AuthProvider>
      </body>
    </html>
  );
}
